### ISSUE TITLE
 91/5000 Hello, I have deployed the code environment on Windows system. After debugging, the error KeyError: '¬neighborOf' always appears. I suspect it's the encoding format of this negation symbol. How can I solve it?

### ISSUE THREAD

**Issue by lh5533223** [DEAL-US/RL-KG#2]

**Comment by miguel-bermudo** [comment]
Hello, all encondings within the application use utf-8, maybe your system does not work on that and it conflicts, try running it in a WSL environment with ubuntu 20.4 and english locale.
